//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Growl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Growl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (build: {0}).
        /// </summary>
        internal static string About_BuildNumber {
            get {
                return ResourceManager.GetString("About_BuildNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find displays, extensions, and updates at:.
        /// </summary>
        internal static string About_FindInformationLabel {
            get {
                return ResourceManager.GetString("About_FindInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growl v{0}.
        /// </summary>
        internal static string About_GrowlVersion {
            get {
                return ResourceManager.GetString("About_GrowlVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons:.
        /// </summary>
        internal static string About_IconInfoLabel {
            get {
                return ResourceManager.GetString("About_IconInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VistaICO Aero Pack -.
        /// </summary>
        internal static string About_IconInfoLabel2 {
            get {
                return ResourceManager.GetString("About_IconInfoLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original idea, inspiration, and logo:.
        /// </summary>
        internal static string About_OriginalLabel {
            get {
                return ResourceManager.GetString("About_OriginalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growl for OSX -.
        /// </summary>
        internal static string About_OriginalLabel2 {
            get {
                return ResourceManager.GetString("About_OriginalLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to forward notifications to
        ///an email account.
        /// </summary>
        internal static string AddComputer_AddEmail {
            get {
                return ResourceManager.GetString("AddComputer_AddEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to forward notifications to
        ///an iPhone.
        /// </summary>
        internal static string AddComputer_AddProwl {
            get {
                return ResourceManager.GetString("AddComputer_AddProwl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname:.
        /// </summary>
        internal static string AddComputer_AddressLabel {
            get {
                return ResourceManager.GetString("AddComputer_AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to forward notifications
        ///to Twitter.
        /// </summary>
        internal static string AddComputer_AddTwitter {
            get {
                return ResourceManager.GetString("AddComputer_AddTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        internal static string AddComputer_FormatLabel {
            get {
                return ResourceManager.GetString("AddComputer_FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward Notifications.
        /// </summary>
        internal static string AddComputer_FormTitle_Forward {
            get {
                return ResourceManager.GetString("AddComputer_FormTitle_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to notifications.
        /// </summary>
        internal static string AddComputer_FormTitle_Subscriptions {
            get {
                return ResourceManager.GetString("AddComputer_FormTitle_Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to manually add a computer
        ///that is not in this list.
        /// </summary>
        internal static string AddComputer_ManualAdd {
            get {
                return ResourceManager.GetString("AddComputer_ManualAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string AddComputer_NameLabel {
            get {
                return ResourceManager.GetString("AddComputer_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string AddComputer_PasswordLabel {
            get {
                return ResourceManager.GetString("AddComputer_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string AddComputer_PortLabel {
            get {
                return ResourceManager.GetString("AddComputer_PortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Any Priority].
        /// </summary>
        internal static string AddEmail_AnyPriority {
            get {
                return ResourceManager.GetString("AddEmail_AnyPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        internal static string AddEmail_EditSMTP {
            get {
                return ResourceManager.GetString("AddEmail_EditSMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address:.
        /// </summary>
        internal static string AddEmail_EmailAddressLabel {
            get {
                return ResourceManager.GetString("AddEmail_EmailAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only forward when priority is at least:.
        /// </summary>
        internal static string AddEmail_MinimumPriorityLabel {
            get {
                return ResourceManager.GetString("AddEmail_MinimumPriorityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string AddEmail_NameLabel {
            get {
                return ResourceManager.GetString("AddEmail_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only forward when idle or away.
        /// </summary>
        internal static string AddEmail_OnlyWhenIdle {
            get {
                return ResourceManager.GetString("AddEmail_OnlyWhenIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        internal static string AddEmail_SMTPDone {
            get {
                return ResourceManager.GetString("AddEmail_SMTPDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string AddEmail_SMTPPasswordLabel {
            get {
                return ResourceManager.GetString("AddEmail_SMTPPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string AddEmail_SMTPPortLabel {
            get {
                return ResourceManager.GetString("AddEmail_SMTPPortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        internal static string AddEmail_SMTPServerLabel {
            get {
                return ResourceManager.GetString("AddEmail_SMTPServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Settings:.
        /// </summary>
        internal static string AddEmail_SMTPSettingsLabel {
            get {
                return ResourceManager.GetString("AddEmail_SMTPSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Authentication.
        /// </summary>
        internal static string AddEmail_SMTPUseAuthentication {
            get {
                return ResourceManager.GetString("AddEmail_SMTPUseAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string AddEmail_SMTPUsernameLabel {
            get {
                return ResourceManager.GetString("AddEmail_SMTPUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SSL.
        /// </summary>
        internal static string AddEmail_SMTPUseSSL {
            get {
                return ResourceManager.GetString("AddEmail_SMTPUseSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Any Priority].
        /// </summary>
        internal static string AddProwl_AnyPriority {
            get {
                return ResourceManager.GetString("AddProwl_AnyPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key:.
        /// </summary>
        internal static string AddProwl_APIKeyLabel {
            get {
                return ResourceManager.GetString("AddProwl_APIKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only forward when priority is at least:.
        /// </summary>
        internal static string AddProwl_MinimumPriorityLabel {
            get {
                return ResourceManager.GetString("AddProwl_MinimumPriorityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string AddProwl_NameLabel {
            get {
                return ResourceManager.GetString("AddProwl_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only forward when idle or away.
        /// </summary>
        internal static string AddProwl_OnlyWhenIdle {
            get {
                return ResourceManager.GetString("AddProwl_OnlyWhenIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to Growl notifications\non another machine.
        /// </summary>
        internal static string AddSubscription_AddGNTP {
            get {
                return ResourceManager.GetString("AddSubscription_AddGNTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Any Priority].
        /// </summary>
        internal static string AddTwitter_AnyPriority {
            get {
                return ResourceManager.GetString("AddTwitter_AnyPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        internal static string AddTwitter_FormatLabel {
            get {
                return ResourceManager.GetString("AddTwitter_FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only forward when priority is at least:.
        /// </summary>
        internal static string AddTwitter_MinimumPriorityLabel {
            get {
                return ResourceManager.GetString("AddTwitter_MinimumPriorityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only forward when idle or away.
        /// </summary>
        internal static string AddTwitter_OnlyWhenIdle {
            get {
                return ResourceManager.GetString("AddTwitter_OnlyWhenIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string AddTwitter_PasswordLabel {
            get {
                return ResourceManager.GetString("AddTwitter_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string AddTwitter_UsernameLabel {
            get {
                return ResourceManager.GetString("AddTwitter_UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (All notifications).
        /// </summary>
        internal static string Applications_AllNotifications {
            get {
                return ResourceManager.GetString("Applications_AllNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        internal static string Applications_ApplicationListHeader {
            get {
                return ResourceManager.GetString("Applications_ApplicationListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a Growl-enabled application registers to send notifications, it will appear in the list to the left and you will be able to customize its settings..
        /// </summary>
        internal static string Applications_NoAppsRegistered_Description {
            get {
                return ResourceManager.GetString("Applications_NoAppsRegistered_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Applications Have Registered Yet.
        /// </summary>
        internal static string Applications_NoAppsRegistered_Title {
            get {
                return ResourceManager.GetString("Applications_NoAppsRegistered_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Type.
        /// </summary>
        internal static string Applications_NotificationListHeader {
            get {
                return ResourceManager.GetString("Applications_NotificationListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display:.
        /// </summary>
        internal static string Applications_Preferences_DisplayLabel {
            get {
                return ResourceManager.GetString("Applications_Preferences_DisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        internal static string Applications_Preferences_DurationLabel {
            get {
                return ResourceManager.GetString("Applications_Preferences_DurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled:.
        /// </summary>
        internal static string Applications_Preferences_EnabledLabel {
            get {
                return ResourceManager.GetString("Applications_Preferences_EnabledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarding:.
        /// </summary>
        internal static string Applications_Preferences_ForwardingLabel {
            get {
                return ResourceManager.GetString("Applications_Preferences_ForwardingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority:.
        /// </summary>
        internal static string Applications_Preferences_PriorityLabel {
            get {
                return ResourceManager.GetString("Applications_Preferences_PriorityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound:.
        /// </summary>
        internal static string Applications_Preferences_SoundLabel {
            get {
                return ResourceManager.GetString("Applications_Preferences_SoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticky:.
        /// </summary>
        internal static string Applications_Preferences_StickyLabel {
            get {
                return ResourceManager.GetString("Applications_Preferences_StickyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Application.
        /// </summary>
        internal static string Applications_RemoveApplication {
            get {
                return ResourceManager.GetString("Applications_RemoveApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Button_Clear {
            get {
                return ResourceManager.GetString("Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        internal static string Button_Later {
            get {
                return ResourceManager.GetString("Button_Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Button_No {
            get {
                return ResourceManager.GetString("Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string Button_Preview {
            get {
                return ResourceManager.GetString("Button_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Default.
        /// </summary>
        internal static string Button_SetAsDefault {
            get {
                return ResourceManager.GetString("Button_SetAsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Button_Yes {
            get {
                return ResourceManager.GetString("Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Forwarding.
        /// </summary>
        internal static string ChooseForwarding_FormTitle {
            get {
                return ResourceManager.GetString("ChooseForwarding_FormTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap close_blue {
            get {
                object obj = ResourceManager.GetObject("close_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close_red {
            get {
                object obj = ResourceManager.GetObject("close_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Default].
        /// </summary>
        internal static string DefaultPreference_Name {
            get {
                return ResourceManager.GetString("DefaultPreference_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display &apos;{0}&apos; is already installed..
        /// </summary>
        internal static string DisplayInstaller_AlreadyInstalled {
            get {
                return ResourceManager.GetString("DisplayInstaller_AlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The definition file &apos;{0}&apos; is invalid.\n\nThe display could not be installed..
        /// </summary>
        internal static string DisplayInstaller_BadDefinitionFile {
            get {
                return ResourceManager.GetString("DisplayInstaller_BadDefinitionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation of the display was cancelled.\n\nThe display was not installed..
        /// </summary>
        internal static string DisplayInstaller_DownloadCancelled {
            get {
                return ResourceManager.GetString("DisplayInstaller_DownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while downloading the display files.\n\nThe display was not installed..
        /// </summary>
        internal static string DisplayInstaller_DownloadError {
            get {
                return ResourceManager.GetString("DisplayInstaller_DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Display.
        /// </summary>
        internal static string DisplayInstaller_FormTitle {
            get {
                return ResourceManager.GetString("DisplayInstaller_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing display....
        /// </summary>
        internal static string DisplayInstaller_Installing {
            get {
                return ResourceManager.GetString("DisplayInstaller_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The display &apos;{0}&apos; was installed successfully..
        /// </summary>
        internal static string DisplayInstaller_NewDisplayInstalledText {
            get {
                return ResourceManager.GetString("DisplayInstaller_NewDisplayInstalledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Display Installed.
        /// </summary>
        internal static string DisplayInstaller_NewDisplayInstalledTitle {
            get {
                return ResourceManager.GetString("DisplayInstaller_NewDisplayInstalledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The definition file &apos;{0}&apos; does not exist.\n\nThe display could not be installed..
        /// </summary>
        internal static string DisplayInstaller_NonexistentDefinitionFile {
            get {
                return ResourceManager.GetString("DisplayInstaller_NonexistentDefinitionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to install the following display?\n\nName: {0}\nAuthor: {1}\nDescription: {2}.
        /// </summary>
        internal static string DisplayInstaller_Prompt {
            get {
                return ResourceManager.GetString("DisplayInstaller_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        internal static string Displays_CreatedBy {
            get {
                return ResourceManager.GetString("Displays_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        internal static string Displays_DisplayListHeader {
            get {
                return ResourceManager.GetString("Displays_DisplayListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find &amp; install additional displays.
        /// </summary>
        internal static string Displays_FindMore {
            get {
                return ResourceManager.GetString("Displays_FindMore", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap email {
            get {
                object obj = ResourceManager.GetObject("email", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growl was unable to start.
        /// </summary>
        internal static string FailedToStart_Caption {
            get {
                return ResourceManager.GetString("FailedToStart_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a listener enabled on Growl&apos;s TCP port ({0}).
        ///
        ///If another version of Growl is already running, please close that version and try again..
        /// </summary>
        internal static string FailedToStart_Message_GNTP {
            get {
                return ResourceManager.GetString("FailedToStart_Message_GNTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a listener enabled on Growl&apos;s legacy UDP port ({0}).
        ///
        ///If another version of Growl is already running, please close that version and try again..
        /// </summary>
        internal static string FailedToStart_Message_UDP {
            get {
                return ResourceManager.GetString("FailedToStart_Message_UDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin &apos;{0}&apos; is already installed..
        /// </summary>
        internal static string ForwarderInstaller_AlreadyInstalled {
            get {
                return ResourceManager.GetString("ForwarderInstaller_AlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The definition file &apos;{0}&apos; is invalid.\n\nThe plugin could not be installed..
        /// </summary>
        internal static string ForwarderInstaller_BadDefinitionFile {
            get {
                return ResourceManager.GetString("ForwarderInstaller_BadDefinitionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation of the plugin was cancelled.\n\nThe plugin was not installed..
        /// </summary>
        internal static string ForwarderInstaller_DownloadCancelled {
            get {
                return ResourceManager.GetString("ForwarderInstaller_DownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while downloading the plugin files.\n\nThe plugin was not installed..
        /// </summary>
        internal static string ForwarderInstaller_DownloadError {
            get {
                return ResourceManager.GetString("ForwarderInstaller_DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Forwarder Plugin.
        /// </summary>
        internal static string ForwarderInstaller_FormTitle {
            get {
                return ResourceManager.GetString("ForwarderInstaller_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin &apos;{0}&apos; was installed successfully..
        /// </summary>
        internal static string ForwarderInstaller_InstalledText {
            get {
                return ResourceManager.GetString("ForwarderInstaller_InstalledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Plugin Installed.
        /// </summary>
        internal static string ForwarderInstaller_InstalledTitle {
            get {
                return ResourceManager.GetString("ForwarderInstaller_InstalledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing plugin....
        /// </summary>
        internal static string ForwarderInstaller_Installing {
            get {
                return ResourceManager.GetString("ForwarderInstaller_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The definition file &apos;{0}&apos; does not exist.\n\nThe plugin could not be installed..
        /// </summary>
        internal static string ForwarderInstaller_NonexistentDefinitionFile {
            get {
                return ResourceManager.GetString("ForwarderInstaller_NonexistentDefinitionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to install the following plugin?\n\nName: {0}\nAuthor: {1}\nDescription: {2}.
        /// </summary>
        internal static string ForwarderInstaller_Prompt {
            get {
                return ResourceManager.GetString("ForwarderInstaller_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growl is paused.
        /// </summary>
        internal static string General_ApplicationPaused {
            get {
                return ResourceManager.GetString("General_ApplicationPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growl is running.
        /// </summary>
        internal static string General_ApplicationRunning {
            get {
                return ResourceManager.GetString("General_ApplicationRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growl is stopped.
        /// </summary>
        internal static string General_ApplicationStopped {
            get {
                return ResourceManager.GetString("General_ApplicationStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically start Growl at login.
        /// </summary>
        internal static string General_AutoStart {
            get {
                return ResourceManager.GetString("General_AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider me idle after            seconds.
        /// </summary>
        internal static string General_IdleSettings_IdleAfter {
            get {
                return ResourceManager.GetString("General_IdleSettings_IdleAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never consider me idle or away.
        /// </summary>
        internal static string General_IdleSettings_NeverIdle {
            get {
                return ResourceManager.GetString("General_IdleSettings_NeverIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Settings.
        /// </summary>
        internal static string General_IdleSettingsTitle {
            get {
                return ResourceManager.GetString("General_IdleSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute all sounds.
        /// </summary>
        internal static string General_SoundSettings_MuteLabel {
            get {
                return ResourceManager.GetString("General_SoundSettings_MuteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Sound:.
        /// </summary>
        internal static string General_SoundSettings_SoundLabel {
            get {
                return ResourceManager.GetString("General_SoundSettings_SoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Settings.
        /// </summary>
        internal static string General_SoundSettingsTitle {
            get {
                return ResourceManager.GetString("General_SoundSettingsTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap generic_application {
            get {
                object obj = ResourceManager.GetObject("generic_application", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon growl_dim {
            get {
                object obj = ResourceManager.GetObject("growl_dim", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon growl_on {
            get {
                object obj = ResourceManager.GetObject("growl_on", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon growl_paused {
            get {
                object obj = ResourceManager.GetObject("growl_paused", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon growl_stopped {
            get {
                object obj = ResourceManager.GetObject("growl_stopped", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string History_Columns_Application {
            get {
                return ResourceManager.GetString("History_Columns_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        internal static string History_Columns_Origin {
            get {
                return ResourceManager.GetString("History_Columns_Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string History_Columns_Text {
            get {
                return ResourceManager.GetString("History_Columns_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string History_Columns_Timestamp {
            get {
                return ResourceManager.GetString("History_Columns_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string History_Columns_Title {
            get {
                return ResourceManager.GetString("History_Columns_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details View.
        /// </summary>
        internal static string History_DetailsView {
            get {
                return ResourceManager.GetString("History_DetailsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No notifications for this date).
        /// </summary>
        internal static string History_NoNotificationsForDate {
            get {
                return ResourceManager.GetString("History_NoNotificationsForDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Days.
        /// </summary>
        internal static string History_NumberOfDaysTitle {
            get {
                return ResourceManager.GetString("History_NumberOfDaysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string History_SortBy_Application {
            get {
                return ResourceManager.GetString("History_SortBy_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string History_SortBy_Date {
            get {
                return ResourceManager.GetString("History_SortBy_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By.
        /// </summary>
        internal static string History_SortByTitle {
            get {
                return ResourceManager.GetString("History_SortByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile View.
        /// </summary>
        internal static string History_TileView {
            get {
                return ResourceManager.GetString("History_TileView", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap internet {
            get {
                object obj = ResourceManager.GetObject("internet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iphone {
            get {
                object obj = ResourceManager.GetObject("iphone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; language pack is already installed..
        /// </summary>
        internal static string LanguageInstaller_AlreadyInstalled {
            get {
                return ResourceManager.GetString("LanguageInstaller_AlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The definition file &apos;{0}&apos; is invalid.\n\nThe language pack could not be installed..
        /// </summary>
        internal static string LanguageInstaller_BadDefinitionFile {
            get {
                return ResourceManager.GetString("LanguageInstaller_BadDefinitionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation of the language pack was cancelled.\n\nThe language pack was not installed..
        /// </summary>
        internal static string LanguageInstaller_DownloadCancelled {
            get {
                return ResourceManager.GetString("LanguageInstaller_DownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while downloading the language pack files.\n\nThe language pack was not installed..
        /// </summary>
        internal static string LanguageInstaller_DownloadError {
            get {
                return ResourceManager.GetString("LanguageInstaller_DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Language Pack.
        /// </summary>
        internal static string LanguageInstaller_FormTitle {
            get {
                return ResourceManager.GetString("LanguageInstaller_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing language pack....
        /// </summary>
        internal static string LanguageInstaller_Installing {
            get {
                return ResourceManager.GetString("LanguageInstaller_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; language pack was installed successfully..
        /// </summary>
        internal static string LanguageInstaller_LanguageInstalledText {
            get {
                return ResourceManager.GetString("LanguageInstaller_LanguageInstalledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Pack Installed.
        /// </summary>
        internal static string LanguageInstaller_LanguageInstalledTitle {
            get {
                return ResourceManager.GetString("LanguageInstaller_LanguageInstalledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The definition file &apos;{0}&apos; does not exist.\n\nThe language pack could not be installed..
        /// </summary>
        internal static string LanguageInstaller_NonexistentDefinitionFile {
            get {
                return ResourceManager.GetString("LanguageInstaller_NonexistentDefinitionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to install the language pack for the following language:  {0}\n\nNOTE: Users running Vista or Windows 7 must have administrator privileges to install language packs..
        /// </summary>
        internal static string LanguageInstaller_Prompt {
            get {
                return ResourceManager.GetString("LanguageInstaller_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart Growl for the changes to take effect..
        /// </summary>
        internal static string LanguageInstaller_RestartRequiredText {
            get {
                return ResourceManager.GetString("LanguageInstaller_RestartRequiredText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap linux {
            get {
                object obj = ResourceManager.GetObject("linux", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        internal static string LiteralString_Always {
            get {
                return ResourceManager.GetString("LiteralString_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to format.
        /// </summary>
        internal static string LiteralString_Format {
            get {
                return ResourceManager.GetString("LiteralString_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Only.
        /// </summary>
        internal static string LiteralString_IdleOnly {
            get {
                return ResourceManager.GetString("LiteralString_IdleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received At.
        /// </summary>
        internal static string LiteralString_ReceivedAt {
            get {
                return ResourceManager.GetString("LiteralString_ReceivedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received From.
        /// </summary>
        internal static string LiteralString_ReceivedFrom {
            get {
                return ResourceManager.GetString("LiteralString_ReceivedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string LiteralString_Seconds {
            get {
                return ResourceManager.GetString("LiteralString_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string LiteralString_Today {
            get {
                return ResourceManager.GetString("LiteralString_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string LiteralString_Yesterday {
            get {
                return ResourceManager.GetString("LiteralString_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading application list....
        /// </summary>
        internal static string Loading_ApplicationList {
            get {
                return ResourceManager.GetString("Loading_ApplicationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading display &apos;{0}&apos; ....
        /// </summary>
        internal static string Loading_Display {
            get {
                return ResourceManager.GetString("Loading_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Displays....
        /// </summary>
        internal static string Loading_Displays {
            get {
                return ResourceManager.GetString("Loading_Displays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading history....
        /// </summary>
        internal static string Loading_History {
            get {
                return ResourceManager.GetString("Loading_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string Loading_Initializing {
            get {
                return ResourceManager.GetString("Loading_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Preferences....
        /// </summary>
        internal static string Loading_Preferences {
            get {
                return ResourceManager.GetString("Loading_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Loading_Ready {
            get {
                return ResourceManager.GetString("Loading_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Growl....
        /// </summary>
        internal static string Loading_Starting {
            get {
                return ResourceManager.GetString("Loading_Starting", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap mac {
            get {
                object obj = ResourceManager.GetObject("mac", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You missed {0} messages while you were away..
        /// </summary>
        internal static string Missed_Summary {
            get {
                return ResourceManager.GetString("Missed_Summary", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap mobile {
            get {
                object obj = ResourceManager.GetObject("mobile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Network_EditComputer {
            get {
                return ResourceManager.GetString("Network_EditComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward notifications to other computers.
        /// </summary>
        internal static string Network_ForwardNotifications {
            get {
                return ResourceManager.GetString("Network_ForwardNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Network_RemoveComputer {
            get {
                return ResourceManager.GetString("Network_RemoveComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to notifications from other computers.
        /// </summary>
        internal static string Network_SubscribeToNotifications {
            get {
                return ResourceManager.GetString("Network_SubscribeToNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string NotifyIcon_ContextMenu_CheckForUpdates {
            get {
                return ResourceManager.GetString("NotifyIcon_ContextMenu_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string NotifyIcon_ContextMenu_Exit {
            get {
                return ResourceManager.GetString("NotifyIcon_ContextMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        internal static string NotifyIcon_ContextMenu_Mute {
            get {
                return ResourceManager.GetString("NotifyIcon_ContextMenu_Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Growl.
        /// </summary>
        internal static string NotifyIcon_ContextMenu_Pause {
            get {
                return ResourceManager.GetString("NotifyIcon_ContextMenu_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Growl.
        /// </summary>
        internal static string NotifyIcon_ContextMenu_Settings {
            get {
                return ResourceManager.GetString("NotifyIcon_ContextMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute.
        /// </summary>
        internal static string NotifyIcon_ContextMenu_Unmute {
            get {
                return ResourceManager.GetString("NotifyIcon_ContextMenu_Unmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpause Growl.
        /// </summary>
        internal static string NotifyIcon_ContextMenu_Unpause {
            get {
                return ResourceManager.GetString("NotifyIcon_ContextMenu_Unpause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growl (not running).
        /// </summary>
        internal static string NotifyIcon_NotRunning {
            get {
                return ResourceManager.GetString("NotifyIcon_NotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growl (paused).
        /// </summary>
        internal static string NotifyIcon_Paused {
            get {
                return ResourceManager.GetString("NotifyIcon_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growl.
        /// </summary>
        internal static string NotifyIcon_Running {
            get {
                return ResourceManager.GetString("NotifyIcon_Running", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap notifyio {
            get {
                object obj = ResourceManager.GetObject("notifyio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap other {
            get {
                object obj = ResourceManager.GetObject("other", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string PrefEnabled_False {
            get {
                return ResourceManager.GetString("PrefEnabled_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string PrefEnabled_True {
            get {
                return ResourceManager.GetString("PrefEnabled_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose....
        /// </summary>
        internal static string PrefForward_Choose {
            get {
                return ResourceManager.GetString("PrefForward_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Forward.
        /// </summary>
        internal static string PrefForward_Never {
            get {
                return ResourceManager.GetString("PrefForward_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency.
        /// </summary>
        internal static string PrefPriority_Emergency {
            get {
                return ResourceManager.GetString("PrefPriority_Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string PrefPriority_High {
            get {
                return ResourceManager.GetString("PrefPriority_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string PrefPriority_Low {
            get {
                return ResourceManager.GetString("PrefPriority_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string PrefPriority_Normal {
            get {
                return ResourceManager.GetString("PrefPriority_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Low.
        /// </summary>
        internal static string PrefPriority_VeryLow {
            get {
                return ResourceManager.GetString("PrefPriority_VeryLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string PrefSound_None {
            get {
                return ResourceManager.GetString("PrefSound_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        internal static string PrefSticky_Always {
            get {
                return ResourceManager.GetString("PrefSticky_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string PrefSticky_Never {
            get {
                return ResourceManager.GetString("PrefSticky_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Idle.
        /// </summary>
        internal static string PrefSticky_WhenIdle {
            get {
                return ResourceManager.GetString("PrefSticky_WhenIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNTP.
        /// </summary>
        internal static string Protocol_Type_GNTP {
            get {
                return ResourceManager.GetString("Protocol_Type_GNTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP.
        /// </summary>
        internal static string Protocol_Type_UDP {
            get {
                return ResourceManager.GetString("Protocol_Type_UDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully configured Growl to forward notifications to Prowl.
        /// </summary>
        internal static string ProwlConfirmation_Text {
            get {
                return ResourceManager.GetString("ProwlConfirmation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prowl Test.
        /// </summary>
        internal static string ProwlConfirmation_Title {
            get {
                return ResourceManager.GetString("ProwlConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;!-- if you dont run a proxy server OR want Growl to auto-detect your IE proxy settings, leave this file as-is --&gt;
        ///&lt;!-- otherwise, if you want to override your default IE proxy address or port OR you need to pass custom authentication credentials, set those values here --&gt;
        ///&lt;appSettings&gt;
        ///  &lt;add key=&quot;ProxyAddress&quot; value=&quot;&quot;/&gt;
        ///  &lt;add key=&quot;ProxyUsername&quot; value=&quot;&quot;/&gt;
        ///  &lt;add key=&quot;ProxyPassword&quot; value=&quot;&quot;/&gt;
        ///  &lt;add key=&quot;ProxyDomain&quot; value=&quot;&quot;/&gt;
        ///&lt;/appSettings&gt;
        ///
        ///
        ///&lt;!--  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string proxy {
            get {
                return ResourceManager.GetString("proxy", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rss {
            get {
                object obj = ResourceManager.GetObject("rss", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow network notifications.
        /// </summary>
        internal static string Security_AllowNetworkNotifications {
            get {
                return ResourceManager.GetString("Security_AllowNetworkNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow clients to subscribe to notifications.
        /// </summary>
        internal static string Security_AllowSubscriptions {
            get {
                return ResourceManager.GetString("Security_AllowSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow notifications from websites.
        /// </summary>
        internal static string Security_AllowWebNotifications {
            get {
                return ResourceManager.GetString("Security_AllowWebNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Security_PasswordManager_DescriptionLabel {
            get {
                return ResourceManager.GetString("Security_PasswordManager_DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Security_PasswordManager_Edit {
            get {
                return ResourceManager.GetString("Security_PasswordManager_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password below as well as a short description to identify the password..
        /// </summary>
        internal static string Security_PasswordManager_Instructions {
            get {
                return ResourceManager.GetString("Security_PasswordManager_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Security_PasswordManager_PasswordLabel {
            get {
                return ResourceManager.GetString("Security_PasswordManager_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Manager.
        /// </summary>
        internal static string Security_PasswordManager_Title {
            get {
                return ResourceManager.GetString("Security_PasswordManager_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require password for local apps.
        /// </summary>
        internal static string Security_RequirePasswordLocalApps {
            get {
                return ResourceManager.GetString("Security_RequirePasswordLocalApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growl.
        /// </summary>
        internal static string SettingsForm_FormTitle {
            get {
                return ResourceManager.GetString("SettingsForm_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string SplashScreen_Loading {
            get {
                return ResourceManager.GetString("SplashScreen_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growl for Windows.
        /// </summary>
        internal static string SplashScreen_Title {
            get {
                return ResourceManager.GetString("SplashScreen_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string SplashScreen_Version {
            get {
                return ResourceManager.GetString("SplashScreen_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin &apos;{0}&apos; is already installed..
        /// </summary>
        internal static string SubscriberInstaller_AlreadyInstalled {
            get {
                return ResourceManager.GetString("SubscriberInstaller_AlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The definition file &apos;{0}&apos; is invalid.\n\nThe plugin could not be installed..
        /// </summary>
        internal static string SubscriberInstaller_BadDefinitionFile {
            get {
                return ResourceManager.GetString("SubscriberInstaller_BadDefinitionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation of the plugin was cancelled.\n\nThe plugin was not installed..
        /// </summary>
        internal static string SubscriberInstaller_DownloadCancelled {
            get {
                return ResourceManager.GetString("SubscriberInstaller_DownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while downloading the plugin files.\n\nThe plugin was not installed..
        /// </summary>
        internal static string SubscriberInstaller_DownloadError {
            get {
                return ResourceManager.GetString("SubscriberInstaller_DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Subscriber Plugin.
        /// </summary>
        internal static string SubscriberInstaller_FormTitle {
            get {
                return ResourceManager.GetString("SubscriberInstaller_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin &apos;{0}&apos; was installed successfully..
        /// </summary>
        internal static string SubscriberInstaller_InstalledText {
            get {
                return ResourceManager.GetString("SubscriberInstaller_InstalledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Plugin Installed.
        /// </summary>
        internal static string SubscriberInstaller_InstalledTitle {
            get {
                return ResourceManager.GetString("SubscriberInstaller_InstalledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing plugin....
        /// </summary>
        internal static string SubscriberInstaller_Installing {
            get {
                return ResourceManager.GetString("SubscriberInstaller_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The definition file &apos;{0}&apos; does not exist.\n\nThe plugin could not be installed..
        /// </summary>
        internal static string SubscriberInstaller_NonexistentDefinitionFile {
            get {
                return ResourceManager.GetString("SubscriberInstaller_NonexistentDefinitionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to install the following plugin?\n\nName: {0}\nAuthor: {1}\nDescription: {2}.
        /// </summary>
        internal static string SubscriberInstaller_Prompt {
            get {
                return ResourceManager.GetString("SubscriberInstaller_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growl.
        /// </summary>
        internal static string SystemNotification_ApplicationName {
            get {
                return ResourceManager.GetString("SystemNotification_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application &apos;{0}&apos; has registered to send notifications..
        /// </summary>
        internal static string SystemNotification_AppRegistered_Text {
            get {
                return ResourceManager.GetString("SystemNotification_AppRegistered_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Registration.
        /// </summary>
        internal static string SystemNotification_AppRegistered_Title {
            get {
                return ResourceManager.GetString("SystemNotification_AppRegistered_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client &apos;{0}&apos; has subscribed to received forwarded notifications..
        /// </summary>
        internal static string SystemNotification_ClientSubscribed_Text {
            get {
                return ResourceManager.GetString("SystemNotification_ClientSubscribed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Subscribed.
        /// </summary>
        internal static string SystemNotification_ClientSubscribed_Title {
            get {
                return ResourceManager.GetString("SystemNotification_ClientSubscribed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a preview of the &apos;{0}&apos; display style..
        /// </summary>
        internal static string SystemNotification_Preview_Text {
            get {
                return ResourceManager.GetString("SystemNotification_Preview_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Display Style.
        /// </summary>
        internal static string SystemNotification_Preview_Title {
            get {
                return ResourceManager.GetString("SystemNotification_Preview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growl is running.
        /// </summary>
        internal static string SystemNotification_Running_Text {
            get {
                return ResourceManager.GetString("SystemNotification_Running_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growl.
        /// </summary>
        internal static string SystemNotification_Running_Title {
            get {
                return ResourceManager.GetString("SystemNotification_Running_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Toolbar_About {
            get {
                return ResourceManager.GetString("Toolbar_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string Toolbar_Applications {
            get {
                return ResourceManager.GetString("Toolbar_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays.
        /// </summary>
        internal static string Toolbar_Displays {
            get {
                return ResourceManager.GetString("Toolbar_Displays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Toolbar_General {
            get {
                return ResourceManager.GetString("Toolbar_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string Toolbar_History {
            get {
                return ResourceManager.GetString("Toolbar_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string Toolbar_Network {
            get {
                return ResourceManager.GetString("Toolbar_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string Toolbar_Security {
            get {
                return ResourceManager.GetString("Toolbar_Security", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap twitter {
            get {
                object obj = ResourceManager.GetObject("twitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete. Starting installation....
        /// </summary>
        internal static string Updater_DownloadComplete {
            get {
                return ResourceManager.GetString("Updater_DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update....
        /// </summary>
        internal static string Updater_DownloadingUpdate {
            get {
                return ResourceManager.GetString("Updater_DownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string Updater_FormTitle {
            get {
                return ResourceManager.GetString("Updater_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growl is up-to-date. Current Version: {1}.
        /// </summary>
        internal static string Updater_GrowlIsUpToDate {
            get {
                return ResourceManager.GetString("Updater_GrowlIsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} of Growl is available. Would you like to update Growl to the latest version? (Current version: {1}).
        /// </summary>
        internal static string Updater_UpdateAvailable {
            get {
                return ResourceManager.GetString("Updater_UpdateAvailable", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap windows {
            get {
                object obj = ResourceManager.GetObject("windows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
